apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ad-service-hpa
  namespace: ads
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: ad-service

  minReplicas: 2
  maxReplicas: 6

  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
